In [3]:
import pandas as pd
import numpy as np
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer, KNNImputer

In [4]:
df = pd.read_csv("synthetic_dataset.csv")
df

,customer_id,first_name,last_name,age,city,signup_date,product_category,purchase_amount_kes,quantity,payment_method,satisfaction_score,is_repeat_customer
0,CUST0001,Michael,Otieno,29.0,Nairobi,2024-01-21,Fashion,6836.99,7.0,NaN,1.0,True
1,CUST0002,NaN,Chebet,56.0,Nakuru,2023-12-20,Electronics,4539.52,8.0,Card,3.0,True
2,CUST0003,Njoroge,Wambui,19.0,Nairobi,2023-02-09,NaN,5064.24,1.0,Bank Transfer,1.0,NaN
3,CUST0004,David,NaN,20.0,Eldoret,2025-03-21,Toys,10153.27,6.0,Bank Transfer,NaN,False
4,CUST0005,Linda,Odhiambo,54.0,Nakuru,2024-06-03,Groceries,11335.14,1.0,NaN,3.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...
95,CUST0096,Susan,Wambui,19.0,Nakuru,2025-10-28,Home & Living,NaN,NaN,Card,5.0,True
96,CUST0097,Mary,Kariuki,52.0,NaN,2024-12-15,Fashion,6390.00,9.0,Cash,1.0,False
97,CUST0098,James,Wanjiru,NaN,Nyeri,NaN,Groceries,14004.38,3.0,NaN,1.0,False
98,CUST0099,Achieng,Mwangi,58.0,Machakos,2023-07-17,Books,13017.75,3.0,Bank Transfer,5.0,NaN
99,CUST0100,Robert,NaN,NaN,Nakuru,2023-02-16,Toys,NaN,2.0,Cash,5.0,False

In [5]:
df.isna()

,customer_id,first_name,last_name,age,city,signup_date,product_category,purchase_amount_kes,quantity,payment_method,satisfaction_score,is_repeat_customer
0,False,False,False,False,False,False,False,False,False,True,False,False
1,False,True,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,True,False,False,False,False,True
3,False,False,True,False,False,False,False,False,False,False,True,False
4,False,False,False,False,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
95,False,False,False,False,False,False,False,True,True,False,False,False
96,False,False,False,False,True,False,False,False,False,False,False,False
97,False,False,False,True,False,True,False,False,False,True,False,False
98,False,False,False,False,False,False,False,False,False,False,False,True
99,False,False,True,True,False,False,False,True,False,False,False,False

In [6]:
df.isna().sum()

customer_id             0
first_name             18
last_name              18
age                     8
city                   16
signup_date            10
product_category       17
purchase_amount_kes    11
quantity               18
payment_method         28
satisfaction_score     16
is_repeat_customer     14
dtype: int64

In [7]:
df_imputer_knn_sklearn = df.copy(deep = True)
df_imputer_knn_sklearn

,customer_id,first_name,last_name,age,city,signup_date,product_category,purchase_amount_kes,quantity,payment_method,satisfaction_score,is_repeat_customer
0,CUST0001,Michael,Otieno,29.0,Nairobi,2024-01-21,Fashion,6836.99,7.0,NaN,1.0,True
1,CUST0002,NaN,Chebet,56.0,Nakuru,2023-12-20,Electronics,4539.52,8.0,Card,3.0,True
2,CUST0003,Njoroge,Wambui,19.0,Nairobi,2023-02-09,NaN,5064.24,1.0,Bank Transfer,1.0,NaN
3,CUST0004,David,NaN,20.0,Eldoret,2025-03-21,Toys,10153.27,6.0,Bank Transfer,NaN,False
4,CUST0005,Linda,Odhiambo,54.0,Nakuru,2024-06-03,Groceries,11335.14,1.0,NaN,3.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...
95,CUST0096,Susan,Wambui,19.0,Nakuru,2025-10-28,Home & Living,NaN,NaN,Card,5.0,True
96,CUST0097,Mary,Kariuki,52.0,NaN,2024-12-15,Fashion,6390.00,9.0,Cash,1.0,False
97,CUST0098,James,Wanjiru,NaN,Nyeri,NaN,Groceries,14004.38,3.0,NaN,1.0,False
98,CUST0099,Achieng,Mwangi,58.0,Machakos,2023-07-17,Books,13017.75,3.0,Bank Transfer,5.0,NaN
99,CUST0100,Robert,NaN,NaN,Nakuru,2023-02-16,Toys,NaN,2.0,Cash,5.0,False

In [8]:
df_imputer_knn_sklearn.isna().sum()

customer_id             0
first_name             18
last_name              18
age                     8
city                   16
signup_date            10
product_category       17
purchase_amount_kes    11
quantity               18
payment_method         28
satisfaction_score     16
is_repeat_customer     14
dtype: int64

In [22]:
num_cols = ['age', 'purchase_amount_kes', 'quantity', 'satisfaction_score']
df_num = df[num_cols].copy()
df_num

     age  purchase_amount_kes  quantity  satisfaction_score
0   29.0              6836.99       7.0                 1.0
1   56.0              4539.52       8.0                 3.0
2   19.0              5064.24       1.0                 1.0
3   20.0             10153.27       6.0                 NaN
4   54.0             11335.14       1.0                 3.0
..   ...                  ...       ...                 ...
95  19.0                  NaN       NaN                 5.0
96  52.0              6390.00       9.0                 1.0
97   NaN             14004.38       3.0                 1.0
98  58.0             13017.75       3.0                 5.0
99   NaN                  NaN       2.0                 5.0

[100 rows x 4 columns]

In [25]:
knn_imp = KNNImputer(n_neighbors = 5)
df_knn = pd.DataFrame(knn_imp.fit_transform(df_num), columns = num_cols)
df_knn

     age  purchase_amount_kes  quantity  satisfaction_score
0   29.0             6836.990       7.0                 1.0
1   56.0             4539.520       8.0                 3.0
2   19.0             5064.240       1.0                 1.0
3   20.0            10153.270       6.0                 3.2
4   54.0            11335.140       1.0                 3.0
..   ...                  ...       ...                 ...
95  19.0             5960.450       1.8                 5.0
96  52.0             6390.000       9.0                 1.0
97  39.2            14004.380       3.0                 1.0
98  58.0            13017.750       3.0                 5.0
99  26.6             8511.024       2.0                 5.0

[100 rows x 4 columns]

In [29]:
from sklearn.impute import SimpleImputer
cat_cols = df.select_dtypes(include ='object').columns
cat_imp = SimpleImputer(strategy = 'most_frequent')
df_cat = pd.DataFrame(cat_imp.fit_transform(df[cat_cols]), columns = cat_cols)
df_cat

,customer_id,first_name,last_name,city,signup_date,product_category,payment_method,is_repeat_customer
0,CUST0001,Michael,Otieno,Nairobi,2024-01-21,Fashion,Card,True
1,CUST0002,Linda,Chebet,Nakuru,2023-12-20,Electronics,Card,True
2,CUST0003,Njoroge,Wambui,Nairobi,2023-02-09,Electronics,Bank Transfer,False
3,CUST0004,David,Chebet,Eldoret,2025-03-21,Toys,Bank Transfer,False
4,CUST0005,Linda,Odhiambo,Nakuru,2024-06-03,Groceries,Card,False
...,...,...,...,...,...,...,...,...
95,CUST0096,Susan,Wambui,Nakuru,2025-10-28,Home & Living,Card,True
96,CUST0097,Mary,Kariuki,Nairobi,2024-12-15,Fashion,Cash,False
97,CUST0098,James,Wanjiru,Nyeri,2023-02-12,Groceries,Card,False
98,CUST0099,Achieng,Mwangi,Machakos,2023-07-17,Books,Bank Transfer,False
99,CUST0100,Robert,Chebet,Nakuru,2023-02-16,Toys,Cash,False

In [30]:
df_final = pd.concat([df_knn,df_cat], axis = 1)
df_final

,age,purchase_amount_kes,quantity,satisfaction_score,customer_id,first_name,last_name,city,signup_date,product_category,payment_method,is_repeat_customer
0,29.0,6836.990,7.0,1.0,CUST0001,Michael,Otieno,Nairobi,2024-01-21,Fashion,Card,True
1,56.0,4539.520,8.0,3.0,CUST0002,Linda,Chebet,Nakuru,2023-12-20,Electronics,Card,True
2,19.0,5064.240,1.0,1.0,CUST0003,Njoroge,Wambui,Nairobi,2023-02-09,Electronics,Bank Transfer,False
3,20.0,10153.270,6.0,3.2,CUST0004,David,Chebet,Eldoret,2025-03-21,Toys,Bank Transfer,False
4,54.0,11335.140,1.0,3.0,CUST0005,Linda,Odhiambo,Nakuru,2024-06-03,Groceries,Card,False
...,...,...,...,...,...,...,...,...,...,...,...,...
95,19.0,5960.450,1.8,5.0,CUST0096,Susan,Wambui,Nakuru,2025-10-28,Home & Living,Card,True
96,52.0,6390.000,9.0,1.0,CUST0097,Mary,Kariuki,Nairobi,2024-12-15,Fashion,Cash,False
97,39.2,14004.380,3.0,1.0,CUST0098,James,Wanjiru,Nyeri,2023-02-12,Groceries,Card,False
98,58.0,13017.750,3.0,5.0,CUST0099,Achieng,Mwangi,Machakos,2023-07-17,Books,Bank Transfer,False
99,26.6,8511.024,2.0,5.0,CUST0100,Robert,Chebet,Nakuru,2023-02-16,Toys,Cash,False

In [35]:
df_final = df_final[df.columns]
df_final

,customer_id,first_name,last_name,age,city,signup_date,product_category,purchase_amount_kes,quantity,payment_method,satisfaction_score,is_repeat_customer
0,CUST0001,Michael,Otieno,29.0,Nairobi,2024-01-21,Fashion,6836.990,7.0,Card,1.0,True
1,CUST0002,Linda,Chebet,56.0,Nakuru,2023-12-20,Electronics,4539.520,8.0,Card,3.0,True
2,CUST0003,Njoroge,Wambui,19.0,Nairobi,2023-02-09,Electronics,5064.240,1.0,Bank Transfer,1.0,False
3,CUST0004,David,Chebet,20.0,Eldoret,2025-03-21,Toys,10153.270,6.0,Bank Transfer,3.2,False
4,CUST0005,Linda,Odhiambo,54.0,Nakuru,2024-06-03,Groceries,11335.140,1.0,Card,3.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...
95,CUST0096,Susan,Wambui,19.0,Nakuru,2025-10-28,Home & Living,5960.450,1.8,Card,5.0,True
96,CUST0097,Mary,Kariuki,52.0,Nairobi,2024-12-15,Fashion,6390.000,9.0,Cash,1.0,False
97,CUST0098,James,Wanjiru,39.2,Nyeri,2023-02-12,Groceries,14004.380,3.0,Card,1.0,False
98,CUST0099,Achieng,Mwangi,58.0,Machakos,2023-07-17,Books,13017.750,3.0,Bank Transfer,5.0,False
99,CUST0100,Robert,Chebet,26.6,Nakuru,2023-02-16,Toys,8511.024,2.0,Cash,5.0,False