In [9]:
from sklearn.impute import KNNImputer
from sklearn.metrics import mean_absolute_error
import numpy as np
import pandas as pd

In [17]:
df = pd.read_csv("synthetic_dataset.csv")
df_num = df.select_dtypes(include = np.number) #int and float
complete_rows = df_num.dropna()
complete_rows

     age  purchase_amount_kes  quantity  satisfaction_score
0   29.0              6836.99       7.0                 1.0
1   56.0              4539.52       8.0                 3.0
2   19.0              5064.24       1.0                 1.0
4   54.0             11335.14       1.0                 3.0
6   19.0             11886.35       1.0                 3.0
8   45.0              7517.42       9.0                 4.0
10  54.0              8333.03       1.0                 2.0
11  49.0              6734.65       1.0                 4.0
12  50.0             13338.02       2.0                 3.0
16  61.0             11470.36       5.0                 1.0
17  43.0              9349.63       7.0                 4.0
18  49.0              1696.62       6.0                 1.0
19  23.0              1444.78       1.0                 2.0
20  49.0             10574.34       5.0                 5.0
24  55.0              1403.96       5.0                 3.0
25  41.0              1455.60       7.0                 3.0
26  22.0             14802.27       5.0                 1.0
27  51.0              5739.21       5.0                 2.0
29  39.0             12229.43       3.0                 5.0
31  33.0             14792.82       5.0                 4.0
35  33.0             11701.77       4.0                 4.0
36  46.0              8464.38       1.0                 1.0
37  20.0              6478.49       1.0                 5.0
38  37.0             13614.04       8.0                 1.0
39  53.0              1845.72       2.0                 1.0
41  43.0               368.03       7.0                 3.0
44  37.0              1958.51       6.0                 5.0
46  24.0              9808.31       2.0                 4.0
48  50.0              8833.86       6.0                 5.0
49  57.0             14440.15       5.0                 3.0
53  18.0              3509.22       5.0                 3.0
55  45.0               379.89       2.0                 1.0
56  42.0             14554.21       3.0                 4.0
57  40.0               838.77       7.0                 5.0
60  59.0             14895.88       6.0                 5.0
64  43.0              7941.85       3.0                 5.0
65  19.0              9515.10       2.0                 5.0
69  54.0              8847.85       1.0                 4.0
71  26.0               872.61       7.0                 5.0
74  36.0             13375.90       5.0                 2.0
76  20.0              9377.96       8.0                 5.0
78  41.0              2984.19       1.0                 1.0
80  41.0              5429.61       8.0                 1.0
81  28.0              8838.11       5.0                 1.0
82  25.0              1350.47       2.0                 2.0
83  53.0             14621.04       6.0                 5.0
84  55.0             14795.92       5.0                 3.0
85  57.0             10532.79       2.0                 3.0
86  37.0              8134.23       3.0                 3.0
88  42.0             12244.17       7.0                 2.0
89  52.0             10334.02       7.0                 4.0
91  46.0             13681.72       8.0                 1.0
92  35.0             12373.55       4.0                 4.0
93  63.0             14257.04       8.0                 3.0
94  35.0             10940.65       4.0                 4.0
96  52.0              6390.00       9.0                 1.0
98  58.0             13017.75       3.0                 5.0

In [23]:
#choosing what values to hide
np.random.seed(1) #seed is same random mask every time you run it
mask = np.random.rand(*complete_rows.shape) < 0.10

In [24]:
#make a copy and an artificial missing value
df_test = complete_rows.copy()
df_test[mask] = np.nan
df_test[mask]

     age  purchase_amount_kes  quantity  satisfaction_score
0   29.0              6836.99       NaN                 1.0
1   56.0                  NaN       8.0                 3.0
4   54.0             11335.14       NaN                 3.0
10  54.0              8333.03       NaN                 NaN
10  54.0              8333.03       NaN                 NaN
11  49.0              6734.65       NaN                 4.0
16  61.0             11470.36       NaN                 1.0
19  23.0              1444.78       NaN                 2.0
20  49.0             10574.34       5.0                 NaN
26   NaN             14802.27       5.0                 1.0
39  53.0              1845.72       NaN                 1.0
44  37.0              1958.51       NaN                 5.0
48  50.0              8833.86       NaN                 5.0
53   NaN                  NaN       NaN                 3.0
53   NaN                  NaN       NaN                 3.0
53   NaN                  NaN       NaN                 3.0
57  40.0                  NaN       7.0                 5.0
64  43.0              7941.85       NaN                 5.0
65   NaN              9515.10       2.0                 5.0
69  54.0                  NaN       NaN                 4.0
69  54.0                  NaN       NaN                 4.0
78  41.0                  NaN       NaN                 1.0
78  41.0                  NaN       NaN                 1.0
82  25.0              1350.47       NaN                 2.0
83  53.0             14621.04       6.0                 NaN
85  57.0             10532.79       2.0                 NaN
88   NaN             12244.17       7.0                 2.0
94   NaN             10940.65       4.0                 NaN
94   NaN             10940.65       4.0                 NaN

In [40]:
#running knn on fake imputed data
imputer = KNNImputer(n_neighbors = 5)
df_test_imputed = pd.DataFrame(imputer.fit_transform(df_test), columns = complete_rows.columns)
df_test_imputed

     age  purchase_amount_kes  quantity  satisfaction_score
0   29.0             6836.990       6.8                 1.0
1   56.0            10843.868       8.0                 3.0
2   19.0             5064.240       1.0                 1.0
3   54.0            11335.140       4.8                 3.0
4   19.0            11886.350       1.0                 3.0
5   45.0             7517.420       9.0                 4.0
6   54.0             8333.030       4.8                 2.8
7   49.0             6734.650       6.8                 4.0
8   50.0            13338.020       2.0                 3.0
9   61.0            11470.360       4.6                 1.0
10  43.0             9349.630       7.0                 4.0
11  49.0             1696.620       6.0                 1.0
12  23.0             1444.780       6.6                 2.0
13  49.0            10574.340       5.0                 3.4
14  55.0             1403.960       5.0                 3.0
15  41.0             1455.600       7.0                 3.0
16  49.2            14802.270       5.0                 1.0
17  51.0             5739.210       5.0                 2.0
18  39.0            12229.430       3.0                 5.0
19  33.0            14792.820       5.0                 4.0
20  33.0            11701.770       4.0                 4.0
21  46.0             8464.380       1.0                 1.0
22  20.0             6478.490       1.0                 5.0
23  37.0            13614.040       8.0                 1.0
24  53.0             1845.720       6.6                 1.0
25  43.0              368.030       7.0                 3.0
26  37.0             1958.510       6.6                 5.0
27  24.0             9808.310       2.0                 4.0
28  50.0             8833.860       5.6                 5.0
29  57.0            14440.150       5.0                 3.0
30  51.4             7500.256       6.0                 3.0
31  45.0              379.890       2.0                 1.0
32  42.0            14554.210       3.0                 4.0
33  40.0             4214.724       7.0                 5.0
34  59.0            14895.880       6.0                 5.0
35  43.0             7941.850       5.6                 5.0
36  42.2             9515.100       2.0                 5.0
37  54.0            10097.818       5.0                 4.0
38  26.0              872.610       7.0                 5.0
39  36.0            13375.900       5.0                 2.0
40  20.0             9377.960       8.0                 5.0
41  41.0             6859.936       6.8                 1.0
42  41.0             5429.610       8.0                 1.0
43  28.0             8838.110       5.0                 1.0
44  25.0             1350.470       6.6                 2.0
45  53.0            14621.040       6.0                 3.4
46  55.0            14795.920       5.0                 3.0
47  57.0            10532.790       2.0                 3.4
48  37.0             8134.230       3.0                 3.0
49  46.0            12244.170       7.0                 2.0
50  52.0            10334.020       7.0                 4.0
51  46.0            13681.720       8.0                 1.0
52  35.0            12373.550       4.0                 4.0
53  63.0            14257.040       8.0                 3.0
54  51.2            10940.650       4.0                 3.2
55  52.0             6390.000       9.0                 1.0
56  58.0            13017.750       3.0                 5.0

In [41]:
#pulling just the masked values
true_vals = complete_rows.values[mask] #true values
imputed_vals =df_test_imputed.values[mask] #what KNN guessed on the artificial blanks

In [42]:
#comparison btwn true and guessed values
mae = mean_absolute_error(true_vals, imputed_vals)
print("MAE:", mae)

MAE: 653.4293793103448

In [43]:
# Per-column MAE (so one big-scale column doesn't dominate the result)
for col in complete_rows.columns:
    col_idx = complete_rows.columns.get_loc(col)
    col_mask = mask[:, col_idx]
    if col_mask.sum() > 0:
        col_mae = mean_absolute_error(
            complete_rows[col].values[col_mask],
            df_test_imputed[col].values[col_mask]
        )
        print(f"{col}: MAE = {col_mae:.2f}")

# Compare to a dumb baseline (just filling with the column mean)
baseline_vals = np.take(complete_rows.mean().values, np.where(mask)[1])
baseline_mae = mean_absolute_error(true_vals, baseline_vals)
print("Baseline (mean-fill) MAE:", baseline_mae)
print("Is KNN better than just using the mean?", mae < baseline_mae)

age: MAE = 20.80
purchase_amount_kes: MAE = 3759.41
quantity: MAE = 3.09
satisfaction_score: MAE = 1.04
Baseline (mean-fill) MAE: 774.5462613430124
Is KNN better than just using the mean? True

In [50]:
#for categorical data
from sklearn.impute import SimpleImputer
df = pd.read_csv("synthetic_dataset.csv")
#columns to mode impute
mode_cols = ['city', 'product_category', 'payment_method', 'is_repeat_customer'] 
#columns to fill with unknown
unknown_cols = ['first_name', 'last_name']
#mode imputation
cat_imp = SimpleImputer(strategy = 'most_frequent')
df_mode_filled = pd.DataFrame(cat_imp.fit_transform(df[mode_cols]), columns = mode_cols)

In [52]:
#filling names with unknown
df_names_filled = df[unknown_cols].fillna("Unknown")
df_names_filled

   first_name last_name
0     Michael    Otieno
1     Unknown    Chebet
2     Njoroge    Wambui
3       David   Unknown
4       Linda  Odhiambo
..        ...       ...
95      Susan    Wambui
96       Mary   Kariuki
97      James   Wanjiru
98    Achieng    Mwangi
99     Robert   Unknown

[100 rows x 2 columns]

In [56]:
#combining the dataframe
df_cat_filled = pd.concat([df_names_filled.reset_index(drop = True), df_mode_filled.reset_index(drop = True)], axis = 1)
df_cat_filled

,first_name,last_name,city,product_category,payment_method,is_repeat_customer
0,Michael,Otieno,Nairobi,Fashion,Card,True
1,Unknown,Chebet,Nakuru,Electronics,Card,True
2,Njoroge,Wambui,Nairobi,Electronics,Bank Transfer,False
3,David,Unknown,Eldoret,Toys,Bank Transfer,False
4,Linda,Odhiambo,Nakuru,Groceries,Card,False
...,...,...,...,...,...,...
95,Susan,Wambui,Nakuru,Home & Living,Card,True
96,Mary,Kariuki,Nairobi,Fashion,Cash,False
97,James,Wanjiru,Nyeri,Groceries,Card,False
98,Achieng,Mwangi,Machakos,Books,Bank Transfer,False
99,Robert,Unknown,Nakuru,Toys,Cash,False

In [57]:
#sanity check
print(df_cat_filled.isna().sum())

first_name            0
last_name             0
city                  0
product_category      0
payment_method        0
is_repeat_customer    0
dtype: int64